### ISSUE TITLE
Rails 4 won't start 

### ISSUE THREAD

**Issue by hakunin** [envato/rails_4_session_flash_backport#10]
Hey,
the Rails.logger isn't available at that point in R4, when you're trying to call `warn` on it, which prevents you from starting a Rails app.

```
michal@17:14:22:~/dev/bis (support/migrate-to-rails-4)$ rails s
/Users/michal/.rvm/gems/ruby-2.1.5/gems/rails_4_session_flash_backport-0.0.3/lib/rails_4_session_flash_backport.rb:11:in `<top (required)>': private method `warn' called for nil:NilClass (NoMethodError)
	from /Users/michal/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/michal/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/michal/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/michal/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/michal/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/michal/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/michal/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:133:in `require'
	from /Users/michal/dev/bis/config/application.rb:5:in `<top (required)>'
	from /Users/michal/.rvm/gems/ruby-2.1.5/gems/railties-4.0.13/lib/rails/commands.rb:74:in `require'
	from /Users/michal/.rvm/gems/ruby-2.1.5/gems/railties-4.0.13/lib/rails/commands.rb:74:in `block in <top (required)>'
	from /Users/michal/.rvm/gems/ruby-2.1.5/gems/railties-4.0.13/lib/rails/commands.rb:71:in `tap'
	from /Users/michal/.rvm/gems/ruby-2.1.5/gems/railties-4.0.13/lib/rails/commands.rb:71:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

**Comment by dgoodlad** [comment]
Thanks @hakunin; that path had obviously never been tested because Rails 4 was only in pre-release when it was written :grin:

We're shipping 0.0.4 which enforces installation in Rails 2/3 projects, since this gem is irrelevant on Rails 4.
